//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.18.3.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

import { DateTime, Duration } from "luxon";

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable()
export class AuthServiceProxy {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    /**
     * @param apiKey (optional) 
     * @return Success
     */
    getToken(apiKey?: string | undefined): Observable<void> {
        let url_ = this.baseUrl + "/auth/get-token?";
        if (apiKey === null)
            throw new Error("The parameter 'apiKey' cannot be null.");
        else if (apiKey !== undefined)
            url_ += "ApiKey=" + encodeURIComponent("" + apiKey) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetToken(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetToken(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<void>;
                }
            } else
                return _observableThrow(response_) as any as Observable<void>;
        }));
    }

    protected processGetToken(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return _observableOf<void>(null as any);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<void>(null as any);
    }
}

@Injectable()
export class ServiceProxy {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    /**
     * @return Success
     */
    publications(): Observable<GetFuturePublicationsResponse> {
        let url_ = this.baseUrl + "/publications";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processPublications(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processPublications(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<GetFuturePublicationsResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<GetFuturePublicationsResponse>;
        }));
    }

    protected processPublications(response: HttpResponseBase): Observable<GetFuturePublicationsResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GetFuturePublicationsResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<GetFuturePublicationsResponse>(null as any);
    }
}

export class GetFuturePublicationsResponse implements IGetFuturePublicationsResponse {
    nextPublication?: GetFuturePublicationsResponseModel;
    publications?: GetFuturePublicationsResponseModel[] | undefined;

    constructor(data?: IGetFuturePublicationsResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.nextPublication = _data["nextPublication"] ? GetFuturePublicationsResponseModel.fromJS(_data["nextPublication"]) : <any>undefined;
            if (Array.isArray(_data["publications"])) {
                this.publications = [] as any;
                for (let item of _data["publications"])
                    this.publications!.push(GetFuturePublicationsResponseModel.fromJS(item));
            }
        }
    }

    static fromJS(data: any): GetFuturePublicationsResponse {
        data = typeof data === 'object' ? data : {};
        let result = new GetFuturePublicationsResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["nextPublication"] = this.nextPublication ? this.nextPublication.toJSON() : <any>undefined;
        if (Array.isArray(this.publications)) {
            data["publications"] = [];
            for (let item of this.publications)
                data["publications"].push(item.toJSON());
        }
        return data;
    }
}

export interface IGetFuturePublicationsResponse {
    nextPublication?: GetFuturePublicationsResponseModel;
    publications?: GetFuturePublicationsResponseModel[] | undefined;
}

export class GetFuturePublicationsResponseModel implements IGetFuturePublicationsResponseModel {
    publishTime?: DateTime | undefined;
    content?: string | undefined;
    image?: string | undefined;

    constructor(data?: IGetFuturePublicationsResponseModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.publishTime = _data["publishTime"] ? DateTime.fromISO(_data["publishTime"].toString()) : <any>undefined;
            this.content = _data["content"];
            this.image = _data["image"];
        }
    }

    static fromJS(data: any): GetFuturePublicationsResponseModel {
        data = typeof data === 'object' ? data : {};
        let result = new GetFuturePublicationsResponseModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["publishTime"] = this.publishTime ? this.publishTime.toString() : <any>undefined;
        data["content"] = this.content;
        data["image"] = this.image;
        return data;
    }
}

export interface IGetFuturePublicationsResponseModel {
    publishTime?: DateTime | undefined;
    content?: string | undefined;
    image?: string | undefined;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new ApiException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((event.target as any).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}